#!/bin/bash

clear
GROUPNAME=nogroup
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
CHECKSYSTEM=$(tail -n +2 /etc/openvpn/server.conf | grep "^username-as-common-name")
# IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
# if [[ "$IP" = "" ]]; thenN
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";
#
# Color
BLUE='\033[0;34m'
GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'
z1='\e[31;1m'  #red
z2='\e[34;1m'  #blue
z3='\e[32;1m'  #green
z4='\e[35;1m'  #magenta
z5='\e[36;1m'  #cyan
z6='\e[33;1m'  #yellow
z7='\e[0m'
cor[1]="\033[1;36m"
cor[2]="\033[1;33m"
cor[3]="\033[1;31m"
cor[5]="\033[1;32m"
cor[4]="\033[0m"
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'

# ads
echo ""
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${RED} #    OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18     #    "
echo -e "${RED} #         BY : Pirakit Khawpleum               #    "
echo -e "${RED} #    FB : https://m.me/pirakrit.khawplum       #    "
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${GREEN} ไอพีเซิฟ: $MYIP "
echo -e "${NC} "
	echo "-------------------------------------------------------" 
        chek=$(cat /etc/issue.net)
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')
	echo -e "\e[032;1mSYSTEM OS:\e[0m  $chek"
	echo -e "\e[032;1mCPU Model:\e[0m $cname"
	echo -e "\e[032;1mNumber Of Cores:\e[0m $cores"
	echo -e "\e[032;1mCPU Frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal Amount Of RAM:\e[0m $tram MB"
	echo -e "\e[032;1mTotal Amount Of Swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem Uptime:\e[0m $up"
	echo "-------------------------------------------------------" 

	echo "-------------------------------------------------------" 
	echo "|||||||||||||||| MyGatherBK-VPN |||||||||||||||||" 
	echo "-------------------------------------------------------"
	echo -e "|${z1} 1${NC}|${z2} User Add)${NC} "
	echo -e "|${z1}00${NC}|${z2} Up Menu Script)${NC} "
    read -p "เลือกหัวข้อเมนูที่ต้องการใช้งาน : " MENU
echo ""
case $MENU in
1) # ==================================================================================================================
	
echo ""
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${RED} #    OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18        #    "
echo -e "${RED} #         BY : Pirakit Khawpleum               #    "
echo -e "${RED} #    FB : https://m.me/pirakrit.khawplum       #    "
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${GREEN} ไอพีเซิฟ: $MYIP "
echo -e "${NC} "
echo ""
read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (วัน): " masaaktif

IP=`dig +short myip.opendns.com @resolver1.opendns.com`
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e ""
echo "====สร้าง User===="
echo "<<<<<Openvpn/ssh>>>>>"
echo "IP Server : $MYIP"
echo "Port Openvpn : 1194"
echo "Port ssh: 22"
echo "Protocal : TCP"
echo "IP Proxy : $MYIP"
echo "Port Proxy : 8080"
echo -e "Username: $Login "
echo -e "Password: $Pass"
echo "Download My Config : http://$MYIP:85/client.ovpn"
echo ""
echo -e "-----------------------------"
echo -e "วันหมดอายุ : $exp"
echo -e "============================="
echo -e "${RED} #         BY : Pirakit Khawpleum               #    "
echo -e ""

	;;
	
	00) # ==================================================================================================================

cd /usr/local/bin
wget -q -O m "https://raw.githubusercontent.com/MyGatherBk/MyAuto/master/Me"
chmod +x /usr/local/bin/m
m

	;;

esac
