#!/bin/bash

clear
GROUPNAME=nogroup
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
CHECKSYSTEM=$(tail -n +2 /etc/openvpn/server.conf | grep "^username-as-common-name")
# IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
# if [[ "$IP" = "" ]]; thenN
IP=$(wget -4qO- "http://whatismyip.akamai.com/")
#

# Color
GRAY='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

# ads
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
if   [[ ! -e /usr/local/bin/Check-Thai ]]; then
	echo -e "MENU SCRIPT ${GRAY}MyGatherBK-VPN${NC}"
	echo ""
	echo -e "|${GRAY} 1${NC}|  เพิ่มชื่อผู้ใช้งาน OpenVPN (Config)"
	echo -e "|${GRAY} 2${NC}|  เพิ่มชื่อผู้ใช้งาน  SSH (HTTP) VPN (OPENVPN)"
	echo -e "|${GRAY} 3${NC}|  ติดตั้ง พร็อกซี่ SQUID PROXY (Port) "
	echo -e "|${GRAY} 4${NC}|  เปิดปิดใช้งาน Openvpn เชื่อมได้ไม่จำกัดเครื่อง"
	echo -e "|${GRAY} 5${NC}|  เปิด-ปิด-รีสตาร์ท การทำงานของระบบ"
	echo -e "|${GRAY} 6${NC}|  ตรวจสอบบัญชีผู้ใช้ SSH ทั้งหมด"
	echo -e "|${GRAY} 7${NC}|  ลบบัญชีผู้ใช้ SSH"
	echo -e "|${GRAY} 8${NC}|  เปลียนรหัสผ่านเซิฟร์เวอร์ ROOT"
	echo -e "|${GRAY} 9${NC}|  ตั้งค่าเวลารีบูทเซิฟเวอร์อัตโนมัติ"
	echo -e "|${GRAY} 10${NC}| ตรวจสอบแบนด์วิดท์ต่อบัญชี"
	echo ""


fi


if [[ ! -e /usr/local/bin/Check-Thai ]]; then
	read -p "Select a Menu Script (NUMBER) : " MENU
fi

case $MENU in
1) # ==================================================================================================================
	
# ads
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
if [[ $CHECKSYSTEM ]]; then
	echo ""
	read -p "ชื่อบัญชีที่ต้องการสร้าง : " -e CLIENT

	if [ $? -eq 0 ]; then
		read -p "รหัสผ่าน : " -e PASSWORD
		echo ""
		echo -e "     ${GRAY}ระบุตัวเลข 30 จะทำให้บัญชีที่สร้างใช้งานไม่ได้ในอีก 30 วัน${NC}"
		read -p "กำหนดวันหมดอายุ : " -e TimeActive

		PROXY=$(grep '^http_port ' /etc/squid/squid.conf | cut -d " " -f 2)
		PROXY=$(grep '^http_port ' /etc/squid3/squid.conf | cut -d " " -f 2)
		useradd -e `date -d "$TimeActive days" +"%Y-%m-%d"` -s /bin/false -M $CLIENT
		EXP="$(chage -l $CLIENT | grep "Account expires" | awk -F": " '{print $2}')"
		echo -e "$PASSWORD\n$PASSWORD\n"|passwd $CLIENT &> /dev/null

		clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
		echo "ชื่อบัญชี : $CLIENT"
		echo "รหัสผ่าน : $PASSWORD"
		echo "หมดอายุในวันที่ : $EXP"
		echo ""
		echo "IP : $IP"
		echo "Port : 22,80,143"
		echo "Proxy Port : $PROXY"
		exit
	else
		echo ""
		echo "ชื่อบัญชีที่ระบุอยู่ในระบบแล้ว"
		echo ""
		read -p "กลับไปที่เมนู (Y or N) : " -e -i Y TOMENU

		if [[ "$TOMENU" = 'Y' ]]; then
			menu
			exit
		elif [[ "$TOMENU" = 'N' ]]; then
			exit
		fi
	fi

else

	echo ""
	read -p "ชื่อบัญชีที่ต้องการสร้าง : " -e CLIENT

	if [[ -e /etc/openvpn/easy-rsa/pki/private/$CLIENT.key ]]; then
		echo ""
		echo "ชื่อบัญชีที่ระบุอยู่ในระบบแล้ว"
		echo ""
		read -p "กลับไปที่เมนู (Y or N) : " -e -i Y TOMENU

		if [[ "$TOMENU" = 'Y' ]]; then
			menu
			exit
		elif [[ "$TOMENU" = 'N' ]]; then
			exit
		fi
	fi

	echo ""
	echo -e "     ${GRAY}ระบุตัวเลข 30 จะทำให้บัญชีที่สร้างใช้งานไม่ได้ในอีก 30 วัน${NC}"
	read -p "กำหนดวันหมดอายุ : " -e TimeActive

newclient () {
	# Generates the custom client.ovpn
	cp /etc/openvpn/client-common.txt ~/$1.ovpn
	echo "<ca>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/ca.crt >> ~/$1.ovpn
	echo "</ca>" >> ~/$1.ovpn
	echo "<cert>" >> ~/$1.ovpn
	sed -ne '/BEGIN CERTIFICATE/,$ p' /etc/openvpn/easy-rsa/pki/issued/$1.crt >> ~/$1.ovpn
	echo "</cert>" >> ~/$1.ovpn
	echo "<key>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/private/$1.key >> ~/$1.ovpn
	echo "</key>" >> ~/$1.ovpn
	echo "<tls-auth>" >> ~/$1.ovpn
	sed -ne '/BEGIN OpenVPN Static key/,$ p' /etc/openvpn/ta.key >> ~/$1.ovpn
	echo "</tls-auth>" >> ~/$1.ovpn
}

	RANDOMFOLDER=$(cat /dev/urandom | tr -dc 'a-zA-Z' | fold -w 4 | head -n 1)
	mkdir /home/vps/public_html/$RANDOMFOLDER
	cd /etc/openvpn/easy-rsa/
	./easyrsa build-client-full $CLIENT nopass
	newclient "$CLIENT"
	cp /root/$CLIENT.ovpn /home/vps/public_html/$RANDOMFOLDER/$CLIENT.ovpn
	rm -f /root/$CLIENT.ovpn
	useradd -e `date -d "$TimeActive days" +"%Y-%m-%d"` -s /bin/false -M $CLIENT
	EXP="$(chage -l $CLIENT | grep "Account expires" | awk -F": " '{print $2}')"
	echo -e "$CLIENT\n$CLIENT\n"|passwd $CLIENT &> /dev/null

	clear
# ads
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
	echo "ชื่อบัญชี : $CLIENT"
	echo "หมดอายุในวันที่ : $EXP"
	echo ""
	echo "ดาวน์โหลดคอนฟิก : http://$IP:85/$RANDOMFOLDER/$CLIENT.ovpn"
	echo ""
	exit

fi

	;;
	2) # ==================================================================================================================

	echo ""
	read -p "ชื่อบัญชีที่ต้องการสร้าง : " -e CLIENT

	if [ $? -eq 0 ]; then
		read -p "รหัสผ่าน : " -e PASSWORD
		echo ""
		echo -e "     ${GRAY}ระบุตัวเลข 30 จะทำให้บัญชีที่สร้างใช้งานไม่ได้ในอีก 30 วัน${NC}"
		read -p "กำหนดวันหมดอายุ : " -e TimeActive

		PROXY=$(grep '^http_port ' /etc/squid/squid.conf | cut -d " " -f 2)
		PROXY=$(grep '^http_port ' /etc/squid3/squid.conf | cut -d " " -f 2)
		useradd -e `date -d "$TimeActive days" +"%Y-%m-%d"` -s /bin/false -M $CLIENT
		EXP="$(chage -l $CLIENT | grep "Account expires" | awk -F": " '{print $2}')"
		echo -e "$PASSWORD\n$PASSWORD\n"|passwd $CLIENT &> /dev/null

		clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
		echo "ชื่อบัญชี : $CLIENT"
		echo "รหัสผ่าน : $PASSWORD"
		echo "หมดอายุในวันที่ : $EXP"
		echo ""
		echo "IP : $IP"
		echo "Port : 22"
		echo "Proxy Port : $PROXY"
		exit
	else
		echo ""
		echo "ชื่อบัญชีที่ระบุอยู่ในระบบแล้ว"
		echo ""
		read -p "กลับไปที่เมนู (Y or N) : " -e -i Y TOMENU

		if [[ "$TOMENU" = 'Y' ]]; then
			menu
			exit
		elif [[ "$TOMENU" = 'N' ]]; then
			exit
		fi
	fi

	;;

	3) # ==================================================================================================================
if [[ -e /etc/squid3/squid.conf ]]; then
	apt-get -y remove --purge squid3
	clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
	echo "Squid Proxy .....Removed."
	exit
elif [[ -e /etc/squid/squid.conf ]]; then
	apt-get -y remove --purge squid
	clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
	echo "Squid Proxy .....Removed."
	exit
fi

read -p "Port Proxy : " -e -i 8080 PROXY

if [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
	apt-get -y install squid3
	cat > /etc/squid3/squid.conf <<END
http_port $PROXY
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl SSH dst xxxxxxxxx-xxxxxxxxx/255.255.255.255
http_access allow SSH
http_access allow localnet
http_access allow localhost
http_access deny all
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
END
	IP2="s/xxxxxxxxx/$IP/g";
	sed -i $IP2 /etc/squid3/squid.conf;
	if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		service squid3 restart
	else
		/etc/init.d/squid3 restart
	fi
	clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
	echo "Squid Proxy .....Install finish."
	echo "IP Proxy : $IP"
	echo "Port Proxy : $PROXY"
	echo ""
	exit

elif [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="18.04"' ]]; then
	apt-get -y install squid
	cat > /etc/squid/squid.conf <<END
http_port $PROXY
acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT
acl SSH dst xxxxxxxxx-xxxxxxxxx/255.255.255.255
http_access allow SSH
http_access allow localnet
http_access allow localhost
http_access deny all
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
END
	IP2="s/xxxxxxxxx/$IP/g";
	sed -i $IP2 /etc/squid/squid.conf;
	/etc/init.d/squid restart
	clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
	echo "Squid Proxy .....Install finish."
	echo "IP Proxy : $IP"
	echo "Port Proxy : $PROXY"
	echo ""
	exit

fi

	;;


	4) # ==================================================================================================================
clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
echo -e "${GRAY}ปรับเปลี่ยนระบบของเซิฟเวอร์ ${NC} "
echo ""
echo -e "|${GRAY}1${NC}| 1 ไฟล์เชื่อมต่อได้ 1 เครื่องเท่านั้น สามารถสร้างไฟล์เพิ่มได้"
echo -e "|${GRAY}2${NC}| 1 ไฟล์เชื่อมต่อได้หลายเครื่อง แต่ต้องสร้างบัญชีเพื่อใช้เชื่อมต่อ"
echo -e "|${GRAY}3${NC}| 1 ไฟล์เชื่อมต่อได้ไม่จำกัดเครื่อง"
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " CHANGESYSTEMSERVER

case $CHANGESYSTEMSERVER in

	1)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
echo "client-to-client" >> /etc/openvpn/server.conf
echo ""
echo "ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 1 เรียบร้อย"
echo ""
service openvpn restart

	;;

	2)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
if [[ "$VERSION_ID" = 'VERSION_ID="7"' ]]; then
	echo "plugin /usr/lib/openvpn/openvpn-auth-pam.so /etc/pam.d/login" >> /etc/openvpn/server.conf
	echo "client-cert-not-required" >> /etc/openvpn/server.conf
	echo "username-as-common-name" >> /etc/openvpn/server.conf
else
	echo "plugin /usr/lib/openvpn/openvpn-plugin-auth-pam.so /etc/pam.d/login" >> /etc/openvpn/server.conf
	echo "client-cert-not-required" >> /etc/openvpn/server.conf
	echo "username-as-common-name" >> /etc/openvpn/server.conf
fi
echo "auth-user-pass" >> /etc/openvpn/client-common.txt
echo ""
echo "ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 2 เรียบร้อย"
echo ""
service openvpn restart

	;;

	3)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
echo "duplicate-cn" >> /etc/openvpn/server.conf
echo ""
echo "ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 3 เรียบร้อย"
echo ""
service openvpn restart

	;;

esac

	;;

	5) # ==================================================================================================================
	
clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
echo -e "เปิด-ปิด-รีสตาร์ท การทำงานของระบบ ${GRAY}Admin MyGatherBK VPN${NC}"
echo ""
echo -e "|${GRAY}1${NC}| OPENVPN"
echo -e "|${GRAY}2${NC}| SSH DROPBEAR"
echo -e "|${GRAY}3${NC}| SQUID PROXY"
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " SERVICE

case $SERVICE in

	1)

	echo ""
	echo -e "	|${GRAY}1${NC}| เปิด"
	echo -e "	|${GRAY}2${NC}| ปิด"
	echo -e "	|${GRAY}3${NC}| รีสตาร์ท"
	echo ""
	read -p "	เลือกหัวข้อที่ต้องการใช้งาน : " SERVICEOPENVPN

	case $SERVICEOPENVPN in

		1)
	service openvpn start
	echo ""
	echo -e "	OpenVPN ${GRAY}STARTED${NC}"
	echo ""
	exit
		;;

		2)
	service openvpn stop
	echo ""
	echo -e "	OpenVPN ${GRAY}STOPPED${NC}"
	echo ""
	exit
		;;

		3)
	service openvpn restart
	echo ""
	echo -e "	OpenVPN ${GRAY}RESTARTED${NC}"
	echo ""
	exit
		;;

	esac

	;;

	2)

	echo ""
	echo -e "	|${GRAY}1${NC}| เปิด"
	echo -e "	|${GRAY}2${NC}| ปิด ${GRAY}หากปิดการทำงานจะไม่สามารถเข้าสู่เทอมินอลได้ ${NC} "
	echo -e "	|${GRAY}3${NC}| รีสตาร์ท"
	echo ""
	read -p "	เลือกหัวข้อที่ต้องการใช้งาน : " SERVICEDROPBEAR

	case $SERVICEDROPBEAR in

		1)

	if [[ -e /etc/default/dropbear ]]; then
		service ssh start
		echo ""
		echo -e "	SSH Dropbear ${GRAY}STARTED${NC}"
		echo ""
		exit
	elif [[ ! -e /etc/default/dropbear ]]; then
		echo ""
		echo "	ยังไม่ได้ติดตั้ง SSH Dropbear"
		echo ""
		exit
	fi
		;;

		2)
	if [[ -e /etc/default/dropbear ]]; then
		service ssh stop
		echo ""
		echo -e "	SSH Dropbear ${GRAY}STOPPED${NC}"
		echo ""
		exit
	elif [[ ! -e /etc/default/dropbear ]]; then
		echo ""
		echo "	ยังไม่ได้ติดตั้ง SSH Dropbear"
		echo ""
		exit
	fi
		;;

		3)
	if [[ -e /etc/default/dropbear ]]; then
		service ssh restart
		echo ""
		echo -e "	SSH Dropbear ${GRAY}RESTARTED${NC}"
		echo ""
		exit
	elif [[ ! -e /etc/default/dropbear ]]; then
		echo ""
		echo "	ยังไม่ได้ติดตั้ง SSH Dropbear"
		echo ""
		exit
	fi
		;;

	esac

	;;

	3)

	echo ""
	echo -e "	|${GRAY}1${NC}| เปิด"
	echo -e "	|${GRAY}2${NC}| ปิด"
	echo -e "	|${GRAY}3${NC}| รีสตาร์ท"
	echo ""
	read -p "	เลือกหัวข้อที่ต้องการใช้งาน : " SERVICEPROXY

	case $SERVICEPROXY in

		1)
	if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="18.04"' ]]; then
		if [[ ! -e /etc/squid/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid start
			echo ""
			echo -e "	Squid Proxy ${GRAY}STARTED${NC}"
			echo ""
			exit
		fi
	elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		if [[ ! -e /etc/squid3/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid3 start
			echo ""
			echo -e "	Squid Proxy ${GRAY}STARTED${NC}"
			echo ""
			exit
		fi
	fi
		;;

		2)
	if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="18.04"' ]]; then
		if [[ ! -e /etc/squid/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid stop
			echo ""
			echo -e "	Squid Proxy ${GRAY}STOPPED${NC}"
			echo ""
			exit
		fi
	elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		if [[ ! -e /etc/squid3/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid3 stop
			echo ""
			echo -e "	Squid Proxy ${GRAY}STOPPED${NC}"
			echo ""
			exit
		fi
	fi
		;;

		3)
	if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="18.04"' ]]; then
		if [[ ! -e /etc/squid/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid restart
			echo ""
			echo -e "	Squid Proxy ${GRAY}RESTARTED${NC}"
			echo ""
			exit
		fi
	elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		if [[ ! -e /etc/squid3/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid3 restart
			echo ""
			echo -e "	Squid Proxy ${GRAY}RESTARTED${NC}"
			echo ""
			exit
		fi
	fi
		;;

	esac

	;;

esac

	;;
	
		6) # ==================================================================================================================

clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
echo "ลำดับ   ชื่อบัญชีผู้ใช้        สถานะ      วันหมดอายุ"
echo ""
C=1
ON=0
OFF=0
while read ONOFF
do
	CLIENTOFFLINE=$(echo -e "${GRAY}OFFLINE${NC}")
	CLIENTONLINE=$(echo -e "${GREEN}ONLINE${NC}")
	ACCOUNT="$(echo $ONOFF | cut -d: -f1)"
	ID="$(echo $ONOFF | grep -v nobody | cut -d: -f3)"
	EXP="$(chage -l $ACCOUNT | grep "Account expires" | awk -F": " '{print $2}')"
	ONLINE="$(cat /etc/openvpn/openvpn-status.log | grep -Eom 1 $ACCOUNT | grep -Eom 1 $ACCOUNT)"
	if [[ $ID -ge 1000 ]]; then
		if [[ -z $ONLINE ]]; then
			printf "%-6s %-15s %-20s %-3s\n" "$C" "$ACCOUNT" "$CLIENTOFFLINE" "$EXP"
			OFF=$((OFF+1))
		else
			printf "%-6s %-15s %-20s %-3s\n" "$C" "$ACCOUNT" "$CLIENTONLINE" "$EXP"
			ON=$((ON+1))
		fi
			C=$((C+1))
        fi
done < /etc/passwd
TOTAL="$(awk -F: '$3 >= '1000' && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo ""
echo ""
echo -e "กำลังเชื่อมต่อ ${GREEN}$ON${NC}  |  ไม่ได้เชื่อมต่อ ${GRAY}$OFF${NC}  |  บัญชีทั้งหมด $TOTAL"
echo ""
exit

	;;

		7) # ==================================================================================================================

clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
read -p "ชื่อบัญชีที่ต้องการลบ : " CLIENT
egrep "^$CLIENT" /etc/passwd >/dev/null

if [ $? -eq 0 ]; then
	if [[ $CHECKSYSTEM ]]; then
		echo ""
		userdel -f $CLIENT
		echo ""
		echo -e "ชื่อบัญชี ${GRAY}$CLIENT${NC} ถูกลบออกจากระบบเรียบร้อยแล้ว"
		echo ""
		exit
	else
		echo ""
		userdel -f $CLIENT
		cd /etc/openvpn/easy-rsa/
		./easyrsa --batch revoke $CLIENT
		EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl
		rm -rf pki/reqs/$CLIENT.req
		rm -rf pki/private/$CLIENT.key
		rm -rf pki/issued/$CLIENT.crt
		rm -rf /etc/openvpn/crl.pem
		cp /etc/openvpn/easy-rsa/pki/crl.pem /etc/openvpn/crl.pem
		chown nobody:$GROUPNAME /etc/openvpn/crl.pem
		echo ""
		echo -e "ชื่อบัญชี ${GRAY}$CLIENT${NC} ถูกลบออกจากระบบเรียบร้อยแล้ว"
		echo ""
		exit
	fi
else
	echo ""
	echo "ไม่มีชื่อบัญชีที่ระบุ"
	echo ""
	exit
fi

	;;		
	
	8) # ==================================================================================================================
#!/bin/bash
clear
clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
echo "             === WELLCOM === "
echo " ======================================"
echo "    กำหนดรหัสผ่านสำหรับล็อกอินด้วยชื่อ root  "
echo " ====================================="
passwd
cat > /etc/ssh/sshd_config <<-END
Port 22
Port 143
Port 80
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
UsePrivilegeSeparation yes
KeyRegenerationInterval 3600
ServerKeyBits 768
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes
ClientAliveInterval 120
ClientAliveCountMax 2
END
service ssh restart
exit
;;

 9) # ==================================================================================================================
 
  if [ ! -e /usr/local/bin/Reboot-Server ]; then
	echo '#!/bin/bash' > /usr/local/bin/Reboot-Server
	echo '' >> /usr/local/bin/Reboot-Server
	echo 'DATE=$(date +"%m-%d-%Y")' >> /usr/local/bin/Reboot-Server
	echo 'TIME=$(date +"%T")' >> /usr/local/bin/Reboot-Server
	echo 'echo "รีบูทเมื่อวันที่ $DATE เวลา $TIME" >> /usr/local/bin/Reboot-Log' >> /usr/local/bin/Reboot-Server
	echo '/sbin/shutdown -r now' >> /usr/local/bin/Reboot-Server
	chmod +x /usr/local/bin/Reboot-Server
fi

clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
echo -e "${GRAY}ตั้งค่าเวลารีบูทเซิฟเวอร์อัตโนมัติ ${NC} "
echo ""
echo -e "|${GRAY}1${NC}| รีบูททุกๆ  1 ชั่วโมง"
echo -e "|${GRAY}2${NC}| รีบูททุกๆ  6 ชั่วโมง"
echo -e "|${GRAY}3${NC}| รีบูททุกๆ 12 ชั่วโมง"
echo -e "|${GRAY}4${NC}| รีบูททุกๆ  1 วัน"
echo -e "|${GRAY}5${NC}| รีบูททุกๆ  7 วัน"
echo -e "|${GRAY}6${NC}| รีบูททุกๆ 30 วัน"
echo -e "|${GRAY}7${NC}| หยุดการรีบูทเซิฟเวอร์"
echo -e "|${GRAY}8${NC}| ตรวจสอบดูบันทึกการรีบูทเซิฟเวอร์"
echo -e "|${GRAY}9${NC}| ลบบันทึกการรีบูทเซิฟเวอร์"
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " REBOOT

case $REBOOT in

	1)

echo "0 * * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 1 ชั่วโมงเรียบร้อยแล้ว"
echo ""
exit

	;;

	2)

echo "0 */6 * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 6 ชั่วโมงเรียบร้อยแล้ว"
echo ""
exit

	;;

	3)

echo "0 */12 * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 12 ชั่วโมงเรียบร้อยแล้ว"
echo ""
exit

	;;

	4)

echo "0 0 * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 1 วันเรียบร้อยแล้ว"
echo ""
exit

	;;

	5)

echo "0 0 * * MON root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 7 วันเรียบร้อยแล้ว"
echo ""
exit

	;;

	6)

echo "0 0 1 * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 30 วันเรียบร้อยแล้ว"
echo ""
exit

	;;

	7)

rm -rf /usr/local/bin/Reboot-Server
echo ""
echo "หยุดการรีบูทเซิฟเวอร์เรียบร้อยแล้ว"
echo ""
exit

	;;

	8)

if [[ ! -e /usr/local/bin/Reboot-Log ]]; then
	echo ""
	echo "ไม่มีบันทึกการรีบูทเซิฟเวอร์"
	echo ""
	exit
else
	echo ""
	cat /usr/local/bin/Reboot-Log
	echo ""
	exit
fi

	;;

	9)

rm -rf /usr/local/bin/Reboot-Log
echo ""
echo "ลบบันทึกการรีบูทเซิฟเวอร์เรียบร้อยแล้ว"
echo ""
exit

	;;

esac

	;;
	10) # ==================================================================================================================
if [[ ! -e /usr/local/bin/Banwidth-Per-Client ]]; then
	apt-get install python
	wget -O /usr/local/bin/Banwidth-Per-Client "https://raw.githubusercontent.com/MyGatherBk/PURE/master/Banwidth-Per-Client"
	chmod +x /usr/local/bin/Banwidth-Per-Client
	clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
	echo ""
	Banwidth-Per-Client
	echo ""
else
	clear
echo ""
echo ""
echo "    =============== OS-32 & 64-bit =================    "
echo "    #                                              #    "
echo "    #       AUTOSCRIPT CREATED BY PIRAKIT          #    "
echo "    #      -----------About Us------------         #    "
echo "    #      OS  DEBIAN 7-8-9  OS  UBUNTU 14-16-18   #    "
echo "    #    Truemoney Wallet : 096-746-2978           #    "
echo "    #               { VPN / SSH }                  #    "
echo "    #         BY : Pirakit Khawpleum               #    "
echo "    #    FB : https://m.me/pirakrit.khawplum       #    "
echo "    #                                              #    "
echo "    =============== OS-32 & 64-bit =================    "
echo ""
echo "    ~¤~ ๏[-ิ_•ิ]๏ ~¤~ Admin MyGatherBK ~¤~ ๏[-ิ_•ิ]๏ ~¤~ "
echo ""
echo " ไอพีเซิฟ:$IP "
echo ""
echo ""
	Banwidth-Per-Client
	echo ""
fi

	;;
00) # ==================================================================================================================

	;;

esac
